<?php

namespace AppBundle\Repository;

/**
 * ALSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ALSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
