<?php

namespace AppBundle\Repository;

/**
 * BulkFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulkFileRepository extends \Doctrine\ORM\EntityRepository
{
}
