<?php

namespace AppBundle\Repository;

/**
 * CustomEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
