<?php

namespace AppBundle\Repository;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
