<?php

namespace AppBundle\Repository;

/**
 * InquiryModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryModeRepository extends \Doctrine\ORM\EntityRepository
{
}
