<?php

namespace AppBundle\Repository;

/**
 * InquiryAssignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryAssignRepository extends \Doctrine\ORM\EntityRepository
{
}
