<?php

namespace AppBundle\Repository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserProfiles()
    {
        $query = $this->getEntityManager()->createQuery(" select f.email,f.username,f.roles,u.id as userID,u.firstName,u.lastName,u.contact,u.profilePic,f.id from AppBundle:User as f join  AppBundle:UserProfile as u where u.userId = f.id");
        $ret = $query->getResult();
        return $ret;
    }
}
