AppBundle\Entity\UserProfile:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: '20'
        lastName:
            type: string
            length: '50'
            nullable: true
        contact:
            type: string
            length: '10'
            nullable: true
        profilePic:
            type: string
            length: 255
            nullable: true
    oneToOne:
        userId:
            targetEntity: User
            joinColumn:
                name: userId
                referencedColumnName: id
    lifecycleCallbacks: {  }
